#!/bin/bash
# Master submit script for all PDE experiments

sbatch scripts/rebuttal/generated_jobs/convection_mlp_ssbroyden.sh
sbatch scripts/rebuttal/generated_jobs/convection_mlp_ssbroyden_seed1.sh
sbatch scripts/rebuttal/generated_jobs/convection_mlp_ssbroyden_seed2.sh
sbatch scripts/rebuttal/generated_jobs/convection_bwler_hat.sh
sbatch scripts/rebuttal/generated_jobs/convection_explicit_bwler.sh
sbatch scripts/rebuttal/generated_jobs/convection_piratenet.sh
sbatch scripts/rebuttal/generated_jobs/reaction_mlp_ssbroyden.sh
sbatch scripts/rebuttal/generated_jobs/reaction_mlp_ssbroyden_seed1.sh
sbatch scripts/rebuttal/generated_jobs/reaction_mlp_ssbroyden_seed2.sh
sbatch scripts/rebuttal/generated_jobs/reaction_bwler_hat.sh
sbatch scripts/rebuttal/generated_jobs/reaction_explicit_bwler.sh
sbatch scripts/rebuttal/generated_jobs/reaction_piratenet.sh
sbatch scripts/rebuttal/generated_jobs/wave_mlp_ssbroyden.sh
sbatch scripts/rebuttal/generated_jobs/wave_mlp_ssbroyden_seed1.sh
sbatch scripts/rebuttal/generated_jobs/wave_mlp_ssbroyden_seed2.sh
sbatch scripts/rebuttal/generated_jobs/wave_bwler_hat.sh
sbatch scripts/rebuttal/generated_jobs/wave_explicit_bwler.sh
sbatch scripts/rebuttal/generated_jobs/wave_piratenet.sh
sbatch scripts/rebuttal/generated_jobs/burgers_mlp_ssbroyden.sh
sbatch scripts/rebuttal/generated_jobs/burgers_bwler_hat.sh
sbatch scripts/rebuttal/generated_jobs/burgers_explicit_bwler.sh
sbatch scripts/rebuttal/generated_jobs/burgers_piratenet.sh
sbatch scripts/rebuttal/generated_jobs/burgers_mlpinterp_temporal.sh
sbatch scripts/rebuttal/generated_jobs/allen_cahn_mlp_ssbroyden.sh
sbatch scripts/rebuttal/generated_jobs/allen_cahn_bwler_hat.sh
sbatch scripts/rebuttal/generated_jobs/allen_cahn_explicit_bwler.sh
sbatch scripts/rebuttal/generated_jobs/allen_cahn_piratenet.sh
sbatch scripts/rebuttal/generated_jobs/allen_cahn_mlpinterp_temporal.sh
sbatch scripts/rebuttal/generated_jobs/poisson_mlp_ssbroyden.sh
sbatch scripts/rebuttal/generated_jobs/poisson_bwler_hat.sh
sbatch scripts/rebuttal/generated_jobs/poisson_explicit_bwler.sh
sbatch scripts/rebuttal/generated_jobs/poisson_piratenet.sh
